import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/commands/create-benefactor-multisig.ts",
    "src/commands/create-benefactor.ts",
    "src/commands/create-operator-multisig.ts",
    "src/commands/create-operator.ts",
    "src/commands/create-vault-multisig.ts",
    "src/commands/create-vault.ts",
    "src/commands/delete-benefactor.ts",
    "src/commands/deposit.ts",
    "src/commands/init.ts",
    "src/commands/mint.ts",
    "src/commands/print-benefactor.ts",
    "src/commands/print-config.ts",
    "src/commands/print-operator.ts",
    "src/commands/print-vault.ts",
    "src/commands/redeem.ts",
    "src/commands/update-benefactor-multisig.ts",
    "src/commands/update-benefactor.ts",
    "src/commands/update-config-multisig.ts",
    "src/commands/update-config.ts",
    "src/commands/update-operator.ts",
    "src/commands/update-vault-multisig.ts",
    "src/commands/update-vault.ts",
    "src/commands/withdraw-multisig.ts",
    "src/commands/withdraw.ts",
    "src/base-command.ts",
  ],
  clean: true,
  sourcemap: true,
  format: ["cjs"],
  dts: false,
  splitting: false,
  minify: false,
  platform: "node",
  target: "node20",
  outDir: "dist",
});
